# Indexação Básica e Fatiamento

In [ ]:
import numpy as np

In [ ]:
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array1[5]

5

In [ ]:
array1[6:9]

array([6, 7, 8])

In [ ]:
array1[5:8] = 12
array1

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
fatia_array = array1[5:8]
print(fatia_array)

[12 12 12]


In [ ]:
fatia_array[1] = 4444
array1

array([   0,    1,    2,    3,    4,   12, 4444,   12,    8,    9])

In [ ]:
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(array2d[0])
print(array2d[0][1])
print(array2d[0, 1])

[1 2 3]
2
2


# Fatiando em Dimensões Maiores

In [ ]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array2d[1, :2]

array([4, 5])