In [ ]:
import numpy as np

In [ ]:
vetor_np = np.arange(1000000)
lista = list(range(1000000))

In [ ]:
%time for _ in range(1000): vetor_np2 = vetor_np * 2

CPU times: user 1.03 s, sys: 37.4 ms, total: 1.07 s
Wall time: 1.08 s


In [ ]:
%time for _ in range(1000): lista2 = [x * 2 for x in lista]

CPU times: user 53.5 s, sys: 1.82 s, total: 55.3 s
Wall time: 55.6 s


In [ ]:
import numpy as np

data = np.random.randn(2, 3)

In [ ]:
data * 10

array([[ 9.17751453, -7.79390653,  8.51234204],
       [-5.69868561, 10.75337802,  6.67967904]])

In [ ]:
data + data

array([[ 1.83550291, -1.55878131,  1.70246841],
       [-1.13973712,  2.1506756 ,  1.33593581]])

# Como criar `ndarrays`?
Forma mais fácil: sequências do Python

In [ ]:
dados_exemplo = [1, 8.9, 0, 3.14, 9]

numpy_array = np.array(dados_exemplo)
numpy_array

array([1.  , 8.9 , 0.  , 3.14, 9.  ])

Sequências aninhadas geram arrays multidimensionais.

In [ ]:
dados_exemplo2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

numpy_array2 = np.array(dados_exemplo2)
numpy_array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Atributos importantes:
- `ndim`
- `shape`
- `dtype`

In [ ]:
print(numpy_array.ndim)
print(numpy_array2.ndim)

1
2


In [ ]:
print(numpy_array.shape)
print(numpy_array2.shape)

(5,)
(2, 4)


In [ ]:
print(numpy_array.dtype)
print(numpy_array2.dtype)

float64
int64


`astype`pode fazer o cast explícito de um tipo.

In [ ]:
array = np.array([1, 2, 3, 4])
print(array.dtype)

float_array = array.astype(np.float64)
print(float_array.dtype)

int64
float64


Outras formas de criar arrays Numpy:
- `zeros`
- `empty`
- `arange`

In [ ]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2, 7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.empty((2, 2, 4))

array([[[2.43296580e-316, 1.03977794e-312, 1.01855798e-312,
         9.54898106e-313],
        [1.06099790e-312, 1.06099790e-312, 1.23075756e-312,
         1.10343781e-312]],

       [[1.01855798e-312, 9.76118064e-313, 1.14587773e-312,
         1.10343781e-312],
        [1.12465777e-312, 2.22809558e-312, 2.14321575e-312,
         0.00000000e+000]]])

In [ ]:
print(np.arange(9))       # Fim
print(np.arange(5, 11))   # Início / Fim

[0 1 2 3 4 5 6 7 8]
[ 5  6  7  8  9 10]


# Aritmética com Arrays Numpy

In [ ]:
array_1 = np.array([1, 2, 3, 4])
array_2 = np.array([5, 6, 7, 8])

In [ ]:
array_1 + array_2

array([ 6,  8, 10, 12])

In [ ]:
array_1 * array_2

array([ 5, 12, 21, 32])

In [ ]:
array_2 ** 2

array([25, 36, 49, 64])