In [ ]:
import pandas as pd

df = pd.read_csv('/content/test.csv')
df

A   B     C    D
0   1   2   3.0  4.0
1   5   6   NaN  8.0
2  10  11  12.0  NaN

In [ ]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

# Eliminando padrões ou colunas com valores faltantes

In [ ]:
df.dropna(axis=0)

A  B    C    D
0  1  2  3.0  4.0

In [ ]:
df.dropna(axis=1)

A   B
0   1   2
1   5   6
2  10  11

In [ ]:
df.dropna(how='all')

A   B     C    D
0   1   2   3.0  4.0
1   5   6   NaN  8.0
2  10  11  12.0  NaN

In [ ]:
df.dropna(thresh=4)

A  B    C    D
0  1  2  3.0  4.0

In [ ]:
df.dropna(subset=['C'])

A   B     C    D
0   1   2   3.0  4.0
2  10  11  12.0  NaN

# "Imputando" valores faltantes

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np

imr = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imr = imr.fit(df.values)

imputed_data = imr.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [ ]:
df.fillna((df.mean()))

A   B     C    D
0   1   2   3.0  4.0
1   5   6   7.5  8.0
2  10  11  12.0  6.0

# Lidando com dados categóricos

In [ ]:
import pandas as pd

df = pd.read_csv('/content/test_categorical.csv')
df

color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [ ]:
size_mapping = { 'XL': 3, 'L': 2, 'M': 1 }
df['size'] = df['size'].map(size_mapping)
df

color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

# Mapeando *features* ordinais

In [ ]:
import numpy as np

class_mapping = { label: idx for idx, label in enumerate(np.unique(df['classlabel'])) }
class_mapping

{'class1': 0, 'class2': 1}

In [ ]:
df['classlabel'] = df['classlabel'].map(class_mapping)
df

color  size  price  classlabel
0  green     1   10.1           1
1    red     2   13.5           0
2   blue     3   15.3           1

In [ ]:
inv_class_mapping = { v: k for k, v in class_mapping.items() }
df['classlabel'] = df['classlabel'].map(inv_class_mapping)
df

color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [ ]:
from sklearn.preprocessing import LabelEncoder

class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values)
y

array([1, 0, 1])

In [ ]:
class_le.inverse_transform(y)

array(['class2', 'class1', 'class2'], dtype=object)

# One-hot Encoding

In [ ]:
df

color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [ ]:
x = df[['color', 'size', 'price']].values
color_le = LabelEncoder()
x[:,0] = color_le.fit_transform(x[:,0])
x

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [ ]:
from sklearn.preprocessing import OneHotEncoder

x = df[['color', 'size', 'price']].values
color_ohe = OneHotEncoder()
color_ohe.fit_transform(x[:,0].reshape(-1, 1)).toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [ ]:
pd.get_dummies(df[['color', 'size', 'price']])

size  price  color_blue  color_green  color_red
0     1   10.1           0            1          0
1     2   13.5           0            0          1
2     3   15.3           1            0          0